# 基本的数据操作

## 数据创建

In [2]:
import torch

# 创建一维张量 (array of range)
# 用法与python的range()函数相同
x = torch.arange(12)
print("Tensor x:\n", x, end="\n\n")

# 查看张量形状
print("Shape of x:", x.shape, end="\n\n")
# 查看张量元素总数
print("Total number of elements in x:", x.numel())  # num of elements

# 改变张量形状
X = x.reshape(3, 4)
print("Reshaped Tensor X:\n", X, end="\n\n")
# 可以使用-1来自动推断张量形状
Y = x.reshape(-1, 4)
print("Reshaped Tensor Y:\n", Y, end="\n\n")
Z = x.reshape(3, -1)
print("Reshaped Tensor Z:\n", Z, end="\n\n")

Tensor x:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Shape of x: torch.Size([12])

Total number of elements in x: 12
Reshaped Tensor X:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped Tensor Y:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped Tensor Z:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])



以上是对一维张量的创建与操作. 以下对矩阵 (多维张量) 进行创建与操作

In [3]:
# 创建指定形状的张量
print("All zeros:\n", torch.zeros((2, 3, 4)), end="\n\n")
print("All ones:\n", torch.ones((2, 3, 4)), end="\n\n")
print("Random numbers:\n", torch.randn(3, 4), end="\n\n")
print("Given data:\n", torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]), end="\n\n")

All zeros:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

All ones:
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Random numbers:
 tensor([[ 1.7909,  1.0899, -1.8142,  0.7892],
        [-0.6737, -0.2567,  0.5218, -0.3231],
        [-1.4233, -0.1328, -0.3276, -0.2521]])

Given data:
 tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])



还可以通过逻辑运算的方式，来创建张量

In [4]:
X = torch.arange(6).reshape(2, 3)
Y = torch.tensor([[0, 1, 2], [5, 4, 3]])
print("X:\n", X, end="\n\n")
print("Y:\n", Y, end="\n\n")
print("X == Y:\n", X == Y, end="\n\n")

X:
 tensor([[0, 1, 2],
        [3, 4, 5]])

Y:
 tensor([[0, 1, 2],
        [5, 4, 3]])

X == Y:
 tensor([[ True,  True,  True],
        [False,  True, False]])



## 数据运算

对两个相同形状的张量做运算, 会按元素做相应运算

In [5]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print("x + y =", x + y, end="\n\n")
print("x - y =", x - y, end="\n\n")
print("x * y =", x * y, end="\n\n")
print("x / y =", x / y, end="\n\n")
print("x ** y =", x ** y, end="\n\n")
print("e ^ x =", torch.exp(x), end="\n\n")
print("Sum of x =", torch.sum(x), end="\n\n")

x + y = tensor([ 3,  4,  6, 10])

x - y = tensor([-1,  0,  2,  6])

x * y = tensor([ 2,  4,  8, 16])

x / y = tensor([0.5000, 1.0000, 2.0000, 4.0000])

x ** y = tensor([ 1,  4, 16, 64])

e ^ x = tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Sum of x = tensor(15)



## 数据操作

### 拼接

In [6]:
# 拼接张量 (concatenate)
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("X:\n", X, end="\n\n")
print("Y:\n", Y, end="\n\n")
print("Concatenate on axis 0:\n", torch.cat((X, Y), dim=0), end="\n\n")
print("Concatenate on axis 1:\n", torch.cat((X, Y), dim=1), end="\n\n")


X:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Y:
 tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

Concatenate on axis 0:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

Concatenate on axis 1:
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])



In [7]:
# 加深对dim的理解
# dim的数字从小到大，表示从外到内
# dim=n, 那么结果的shape的第n维 = 被拼接向量的第n维相加

# dim=0, 两者的shape第0维的数字相加, [3+3, 4]
print("Shape of concatenated tensor on axis 0:", torch.cat((X, Y), dim=0).shape, end="\n\n")
# dim=1, 两者的shape第1维的数字相加, [3, 4+4]
print("Shape of concatenated tensor on axis 1:", torch.cat((X, Y), dim=1).shape, end="\n\n")

Shape of concatenated tensor on axis 0: torch.Size([6, 4])

Shape of concatenated tensor on axis 1: torch.Size([3, 8])



In [8]:
# 因此, 若要在dim=n上拼接, 那么两者除了dim=n的维度外, 其他维度的shape必须相同

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.arange(16, dtype=torch.float32).reshape((4, 4))
torch.cat((X, Y), dim=0)  # ok
torch.cat((X, Y), dim=1)  # error

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 4 for tensor number 1 in the list.

### 广播机制

上述操作是在两个形状相同的张量中进行的. 但在形状不同的时候, 其实可以使用广播机制来按元素进行操作

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print("a:\n", a, end="\n\n")
print("b:\n", b, end="\n\n")

# 可以看作b的每一列都分别加上a的每一行
print("a + b:\n", a + b, end="\n\n")

# shape: [3, 1] + [1, 2] = [3, 2]
print("Shape of a + b:", (a + b).shape, end="\n\n")

a:
 tensor([[0],
        [1],
        [2]])

b:
 tensor([[0, 1]])

a + b:
 tensor([[0, 1],
        [1, 2],
        [2, 3]])

Shape of a + b: torch.Size([3, 2])



### 索引和切片

In [ ]:
# 与python list操作一样
print("X[-1] = ", X[-1], end="\n\n")    # 最后一行, 即第1维的最后一个元素
print("X[1:3] = ", X[1:3], end="\n\n")  # 第1, 2行, 即第1维的第1个元素到第3个元素
print("X[1, 2] = ", X[1, 2], end="\n\n")    # 第1行第2列, 即第1维的第1个元素的第2个元素
print("X[1:3, 2:4] = \n", X[1:3, 2:4], end="\n\n")  # 第1, 2行, 第2, 3列, 即第1维的第1个元素到第3个元素, 第2维的第2个元素到第4个元素

# 可以发现:
# 1. 用逗号隔开的索引, 代表对不同维度的索引
# 2. 用冒号隔开的索引, 代表对同一维度的索引

X[-1] =  tensor([ 8,  9, 10, 11])

X[1:3] =  tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

X[1, 2] =  tensor(6)

X[1:3, 2:4] = 
 tensor([[ 6,  7],
        [10, 11]])



### 在赋值时节省内存

重新赋值 (形如`X = X + Y`) 会为`X`重新分配一个地址. 我们希望避免这种写法
原因:
1. 避免不必要的内存分配, 尽量原地更新参数值
2. 如果不原地更新, 其他引用仍然会指向旧的内存位置, 那么某些代码可能会无意中引用旧的参数

In [13]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.arange(12, 24, dtype=torch.float32).reshape((3, 4))

# X + Y 会重新分配内存
before = id(X)
X = X + Y
after1 = id(X)
print("Whether the address of X changed if X = X + Y: ", before == after1)

# 使用切片表示法或+=号, 则不会重新分配
before = id(X)
X[:] = X + Y
after2 = id(X)
print("Whether the address of X changed if X[:] = X + Y: ", before == after2)

before = id(X)
X += Y
after3 = id(X)
print("Whether the address of X changed if X += Y: ", before == after3)

Whether the address of X changed if X = X + Y:  False
Whether the address of X changed if X[:] = X + Y:  True
Whether the address of X changed if X += Y:  True
